cicd: Update config cicd

diff --git a/.github/workflows/Docker image CI.yml b/.github/workflows/Docker image CI.yml
--- a/.github/workflows/Docker image CI.yml
+++ b/.github/workflows/Docker image CI.yml
@@ -1,4 +1,4 @@
-name: Docker Backend CI/CD
+name: Backend CI/CD
 
 on:
   push:
@@ -32,10 +32,53 @@ jobs:
           username: ${{ secrets.DOCKER_USERNAME }}
           password: ${{ secrets.DOCKER_TOKEN }}
 
-      - name: Build backend image
+      - name: Build and Push docker image
         run: |
-          docker build --platform linux --tag mateovalenzuela/apiinversiones:latest .
+          IMAGE_TAG=${{ secrets.DOCKER_IMAGE_NAME }}:${{ github.sha }}
+          docker build --platform linux --tag $IMAGE_TAG --tag ${{ secrets.DOCKER_IMAGE_NAME }}:latest .
+          docker push $IMAGE_TAG
+          docker push ${{ secrets.DOCKER_IMAGE_NAME }}:latest
 
-      - name: Publish backend image to Docker Hub
+          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV  # Exporta la variable IMAGE_TAG
+
+      - name: Update Docker Compose
         run: |
-          docker push mateovalenzuela/apiinversiones:latest
+          sed -i "s|image: ${{ secrets.DOCKER_IMAGE_NAME }}:.*|image: $IMAGE_TAG|g" docker-compose.yml
+
+      - name: Log in to Azure
+        uses: azure/login@v1
+        with:
+          creds: ${{ secrets.AZURE_CREDENTIALS }}
+
+      - name: Deploy with Docker Compose
+        run: |
+          az webapp config container set \
+            --name ${{ secrets.AZURE_WEBAPP_NAME }} \
+            --resource-group ${{ secrets.RESOURCE_GROUP_NAME }} \
+            --multicontainer-config-type compose \
+            --multicontainer-config-file ./docker-compose.yml
+
+      - name: Restart Azure App Service
+        run: |
+          az webapp stop --name ${{ secrets.AZURE_WEBAPP_NAME }} --resource-group ${{ secrets.RESOURCE_GROUP_NAME }}
+          az webapp start --name ${{ secrets.AZURE_WEBAPP_NAME }} --resource-group ${{ secrets.RESOURCE_GROUP_NAME }}
+
+      - name: Validate Deployment
+        run: |
+          MAX_RETRIES=10  # Número máximo de intentos
+          RETRY_DELAY=60  # Tiempo de espera entre intentos (en segundos)
+
+          for ((i=1; i<=MAX_RETRIES; i++)); do
+              RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" https://${{ secrets.URL_APP }})
+                
+              if [ "$RESPONSE" -eq 200 ]; then
+                  echo "Deployment successful! HTTP status $RESPONSE"
+                  exit 0
+              fi
+
+              echo "Attempt $i/$MAX_RETRIES failed with HTTP status $RESPONSE. Retrying in $RETRY_DELAY seconds..."
+              sleep $RETRY_DELAY
+          done
+
+          echo "Deployment failed after $MAX_RETRIES attempts. HTTP status $RESPONSE"
+          exit 1
